### ISSUE TITLE
[FEATURE] Option to have seperate saves vs checks for attributes

### ISSUE THREAD

**Issue by oestred** [Larkinabout/fvtt-token-action-hud-dnd5e#15]
The original Token Action HUD has a seperate listing for attribute checks and saving throws. The new one combines them and pops up a box asking you to choose which roll type it is.

New feature = Add a setting to let you have both attribue checks and saving throws like the old module did.  The reason why is that requires 1 click to do so is fast. Now you have to click another choice which takes longer and seems unnecessary. Adding an option lets people do it how they like, new or classic  way. The one click ability is one of the wodnerful things about Token Action Hud.

**Comment by Larkinabout** [comment]
Think I'm going to need a help guide soon as this one's come up a few times now!

Checks and Saving Throws still exist, they moved to subcategories rather than a module setting.

1. Unlock the HUD.
2. Right-click the Attributes category (or anywhere you want to put them) to open the dialog.
3. Select 'Checks' and 'Saving Throws' from the list.
4. Remove 'Abilities' from the list.
5. Click 'Accept'.
6. Lock the HUD.

There are lots more subcategories for customisation of the HUD now and they can all be added or removed in this way.

**Comment by oestred** [comment]
Ah, yes, I see that now. Thank you for the info. I see the different choices in there now. 

Token Action Hud is in my top two must have modules that makes such a difference, so a sincere thank you for all your work on it.

I think if you put info on the main description page on the GitGub then people can see the directions there if they come to the GitHub.
