### ISSUE TITLE
[FEATURE] Separate buttons for ability checks and saves

### ISSUE THREAD

**Issue by nschoenwald** [Larkinabout/fvtt-token-action-hud-dnd5e#9]
**Describe your idea**
I would love it if ability checks and saves were separated in the hud, so that you don't need the pop-up that is currently implemented.

**Comment by Larkinabout** [comment]
Hi @nschoenwald, these should be available already you just need to add the 'Checks' and 'Saves' subcategories instead of the 'Abilities' one.

**Comment by nschoenwald** [comment]
Can I set this up for my players as well or does this have to be done for every user?

**Comment by Larkinabout** [comment]
> Can I set this up for my players as well or does this have to be done for every user?

It's per user, so you'd need to log in as them to set it up on their behalf. I'll add a feature issue for copying HUD setups, but it's likely to be an all or nothing approach as the new HUD is all about customisation on-the-fly rather than hardcoded settings. Let me know if there's anything that would make customisation of the HUD easier.

**Comment by nschoenwald** [comment]
Ah, it's not a problem if I can set it up for them on my machine. I was
worried that it would be cookie based. Thanks a lot for the quick help!

Larkinabout ***@***.***> schrieb am Do., 26. Jan. 2023, 17:42:
